apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logrotate
spec:
  selector: 
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
        id: logrotate
      name: logrotate
    spec:
      containers:
      - name: logrotate-es
        image: blacklabelops/logrotate
        securityContext:
          privileged: true
        volumeMounts:
         - name: containers
           mountPath: /var/lib/docker/containers
         - name: varlog
           mountPath: /var/log/docker
         - name: logs
           mountPath: /logs
        env:
        #日志路径
        - name: LOGS_DIRECTORIES
          value: "/var/lib/docker/containers /var/log/docker"
        #日志轮循周期,值: daily,weekly,yearly
        - name: LOGROTATE_INTERVAL
          value: "daily"
        # #旧文件存放目录
        # - name: LOGROTATE_OLDDIR
        #   value: "/logs"
        #cron 执行周期
        - name: LOGROTATE_CRONSCHEDULE
          value: "0 0 0 * * *"
        #时区
        - name: TZ
          value: "Asia/Shanghai"
        #大小
        - name: LOGROTATE_MINSIZE
          value: "10M"
         #旧文件数量
        - name: LOGROTATE_COPIES
          value: "5"
      volumes:
         - hostPath:
             path: /var/lib/docker/containers
           name: containers
         - hostPath:
             path: /var/log/docker
           name: varlog
         - hostPath:
             path: /var/log/containers/
           name: logs